addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - '2.7'

virtualenv:
  system_site_packages: true

cache:
  directories:
    - /home/travis/build/OCA

env:
  matrix:
  - VERSION="8.0" SPHINX="1"
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0" SPHINX="0"
  - secure: "lazdZGpkqFTQiu44grYAqKcaGh0cVTBlrHcBxxs43K/OH4Uc2AjMBty83zKc0ZgzizrNOsfK3Z3UHLmTNI92Vi3PtgGzA9dUmiReGO6QcE9P31Geg4pN/1Fwosv6aSpG3hejJJ8ZYpMbEPJkZyjTVpdM2r1VEcqEvFQ2xR5bEUg="

install:
  - git clone https://github.com/sylvain-garancher/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools -b add-sphinx-documentation
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

services:
  - postgresql

script:
  - travis_run_tests
